# -*- coding: utf-8 -*-
"""P3 _Learning Drug‑Drug Interactions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s3fGnUxsbPipP94l9zZfkHM7hkjOXYMW

# Phase 3: MUDI dataset to train a dual‑encoder model that learns drug‑drug interaction categories.

This notebook builds a dual‑encoder model that learns how two drugs interact. The model uses the pre‑trained single‑drug encoder from Phase 2 (weights shared for both drugs) and adds an interaction layer followed by a classification head. Training is performed on the MUDI dataset with three interaction classes (synergism, antagonism, new effect).

**Steps in this notebook:**

- Load the pre‑trained encoder weights.
- Define a dual‑encoder architecture with weight sharing.
- Add an interaction layer (concatenation + optional element‑wise product).
- Attach a classification head.
- Load the pre‑processed MUDI graph data.
- Train the model using cross‑entropy loss with class weights.
- Evaluate on the held‑out test set.
- Save the fine‑tuned model for Phase 4.
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install rdkit
!pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-2.0.0+cu118.html

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import GCNConv, GATConv, global_mean_pool
from torch_geometric.loader import DataLoader
import os
import numpy as np
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

# Set device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

base_path = '/content/drive/MyDrive/FYP/IRP/Data'
processed_dir = os.path.join(base_path, 'processed_graphs')

"""## 1. Load the Pre‑trained Encoder

The encoder architecture match the one used in Phase 2. It consists of three graph convolutional layers (GCN, GAT, GCN) followed by global mean pooling. Only the convolutional layers are loaded; the final fully connected layers are discarded because they were specific to the regression task.
"""

# Define the same encoder class as in Phase 2 (without the final regression heads)
class SingleDrugEncoder(nn.Module):
    def __init__(self, node_feat_dim, hidden_dim=128):
        super().__init__()
        self.conv1 = GCNConv(node_feat_dim, hidden_dim)
        self.conv2 = GATConv(hidden_dim, hidden_dim, heads=4, concat=False)
        self.conv3 = GCNConv(hidden_dim, hidden_dim)

    def forward(self, x, edge_index, batch):
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = self.conv2(x, edge_index)
        x = F.relu(x)
        x = self.conv3(x, edge_index)
        x = F.relu(x)
        # Global pooling to obtain a graph-level embedding
        x = global_mean_pool(x, batch)  # shape: (batch_size, hidden_dim)
        return x

# Determine node feature dimension from one of the saved graphs
# Load one graph to inspect (any file will do)
temp_graphs = torch.load(os.path.join(processed_dir, 'mudi_train.pt'), weights_only=False)
sample_graph_a = temp_graphs[0][0]  # first graph of first pair
node_feat_dim = sample_graph_a.x.shape[1]
hidden_dim = 128

# Create encoder instance and load pre‑trained weights
encoder = SingleDrugEncoder(node_feat_dim, hidden_dim).to(device)

# Load the saved encoder state dict (conv layers only)
encoder_state = torch.load(os.path.join(processed_dir, 'pretrained_encoder.pt'), weights_only=False)
encoder.conv1.load_state_dict(encoder_state['conv1'])
encoder.conv2.load_state_dict(encoder_state['conv2'])
encoder.conv3.load_state_dict(encoder_state['conv3'])

print("Pre‑trained encoder loaded successfully.")

"""The architecture combines Graph Convolutional Networks (GCN) and Graph Attention Networks (GAT) to capture complementary aspects of molecular structure. GCN layers aggregate information from neighboring atoms, learning local chemical environments effectively (Kipf and Welling, 2017). GAT layers introduce attention mechanisms that weigh the importance of different neighbors, allowing the model to focus on bonds that are most relevant for toxicity prediction (Veličković et al., 2018). Global mean pooling then summarizes the atom‑level features into a fixed‑size graph representation, which is passed through fully connected layers to output a single toxicity value. This combination is widely adopted in molecular property prediction because it balances expressivity with computational efficiency (Yang et al., 2019).

## 2. Build the Dual‑Encoder Model with Interaction Layer

The dual‑encoder model uses two copies of the same encoder with **shared weights**. This ensures that the same molecular features are extracted from both drugs. The embeddings **E_A** and **E_B** are then combined in an interaction layer.

Several interaction methods are possible:
- **Concatenation**: E_interaction = [E_A, E_B]
- **Element‑wise product**: E_interaction = E_A * E_B
- **Concatenation + product**: E_interaction = [E_A, E_B, E_A * E_B]

Concatenation alone already allows the subsequent layers to learn multiplicative interactions implicitly. Here, both concatenation and element‑wise product are combined for richer representation.
"""

class DualEncoderDDI(nn.Module):
    def __init__(self, encoder, hidden_dim=128, num_classes=3):
        super().__init__()
        # Shared encoder
        self.encoder = encoder
        # Interaction layer: combine embeddings
        # After pooling, each embedding has dimension hidden_dim
        # Combined representation will be 3 * hidden_dim (concat + product)
        combined_dim = hidden_dim * 3  # E_A, E_B, E_A * E_B
        # Classification head
        self.classifier = nn.Sequential(
            nn.Linear(combined_dim, 64),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(64, num_classes)
        )

    def forward(self, data_a, data_b):
        # Encode each drug
        emb_a = self.encoder(data_a.x, data_a.edge_index, data_a.batch)
        emb_b = self.encoder(data_b.x, data_b.edge_index, data_b.batch)

        # Interaction features
        prod = emb_a * emb_b
        combined = torch.cat([emb_a, emb_b, prod], dim=1)  # shape: (batch_size, 3*hidden_dim)

        # Classification
        out = self.classifier(combined)
        return out

"""## 3. Load the MUDI Dataset

The MUDI dataset was saved in Phase 1 as two files: **mudi_train.pt** and **mudi_test.pt**. Each file contains a tuple **(graphs_a, graphs_b, labels)**. A custom dataset class is created to feed these into the model.
"""

class MUDIDataset(torch.utils.data.Dataset):
    def __init__(self, graphs_a, graphs_b, labels):
        self.graphs_a = graphs_a
        self.graphs_b = graphs_b
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return self.graphs_a[idx], self.graphs_b[idx], self.labels[idx]

# Load data
train_data = torch.load(os.path.join(processed_dir, 'mudi_train.pt'), weights_only=False)
test_data = torch.load(os.path.join(processed_dir, 'mudi_test.pt'), weights_only=False)

train_dataset = MUDIDataset(train_data[0], train_data[1], train_data[2])
test_dataset = MUDIDataset(test_data[0], test_data[1], test_data[2])

print(f"Train samples: {len(train_dataset)}")
print(f"Test samples: {len(test_dataset)}")

"""## 4. Create DataLoaders

A custom collate function is needed to combine two separate graphs into a batch. PyTorch Geometric’s **Batch** class handles this automatically when given a list of graphs. The collate function will take a batch of tuples **(graph_a, graph_b, label)** and return batched graphs for A and B along with labels.
"""

from torch_geometric.data import Batch

def collate_ddi(batch):
    graphs_a = [item[0] for item in batch]
    graphs_b = [item[1] for item in batch]
    labels = [item[2] for item in batch]
    batch_a = Batch.from_data_list(graphs_a)
    batch_b = Batch.from_data_list(graphs_b)
    return batch_a, batch_b, torch.tensor(labels, dtype=torch.long)

batch_size = 64
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, collate_fn=collate_ddi)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, collate_fn=collate_ddi)

"""## 5. Set Up Training Components

- **Model**: DualEncoderDDI with shared encoder.
- **Loss**: Cross‑entropy loss. Class weights are loaded from Phase 1 to handle imbalance.
- **Optimizer**: Adam with a moderate learning rate.
"""

# Load class weights
class_weights = torch.load(os.path.join(processed_dir, 'mudi_class_weights.pt'), weights_only=False).to(device)

# Instantiate model
model = DualEncoderDDI(encoder, hidden_dim=128, num_classes=3).to(device)

# Loss and optimizer
criterion = nn.CrossEntropyLoss(weight=class_weights)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

print("Model, loss, and optimizer ready.")

"""## 6. Training Loop

The model is trained for several epochs. After each epoch, accuracy on the test set is computed to monitor progress. Early stopping could be added, but here a fixed number of epochs is used for simplicity.
"""

def train_epoch(loader):
    model.train()
    total_loss = 0
    for batch_a, batch_b, labels in loader:
        batch_a = batch_a.to(device)
        batch_b = batch_b.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()
        out = model(batch_a, batch_b)
        loss = criterion(out, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item() * len(labels)
    return total_loss / len(loader.dataset)

def evaluate(loader):
    model.eval()
    all_preds = []
    all_labels = []
    with torch.no_grad():
        for batch_a, batch_b, labels in loader:
            batch_a = batch_a.to(device)
            batch_b = batch_b.to(device)
            labels = labels.to(device)
            out = model(batch_a, batch_b)
            preds = out.argmax(dim=1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
    acc = accuracy_score(all_labels, all_preds)
    precision, recall, f1, _ = precision_recall_fscore_support(all_labels, all_preds, average='weighted')
    return acc, precision, recall, f1

num_epochs = 20
for epoch in range(num_epochs):
    train_loss = train_epoch(train_loader)
    test_acc, test_prec, test_rec, test_f1 = evaluate(test_loader)
    print(f"Epoch {epoch+1:2d}/{num_epochs} | Train Loss: {train_loss:.4f} | Test Acc: {test_acc:.4f} | Prec: {test_prec:.4f} | Rec: {test_rec:.4f} | F1: {test_f1:.4f}")

"""## 7. Save the Fine‑Tuned Model

The entire model (encoder + interaction layer + classifier) is saved for later use in Phase 4.
"""

torch.save(model.state_dict(), os.path.join(processed_dir, 'ddi_interaction_model.pt'))
print("Model saved as 'ddi_interaction_model.pt'.")

"""## 8. Summary

This notebook trained a dual‑encoder GNN on the MUDI dataset to classify drug‑drug interactions. The model uses a shared pre‑trained encoder, concatenates the embeddings with their element‑wise product, and applies a classifier. Performance on the test set shows whether the model has learned meaningful interaction patterns.

The saved model will be used in Phase 4, where the classification head will be replaced with a regression head to predict continuous DDI LD₅₀ values.
"""